'use strict'

const fs = require('fs');

/**
 * InterpolateSWPlugin is a webpack plugin that will replace in your own service worker the following variables:
 * 
 *  - "%SW_CACHE_VERSION%": An automatically generated version for your cache. Use "%SW_CACHE_VERSION%"" variable in your SW. Please note the double quotes around "%SW_CACHE_VERSION%":
 *    
 *      caches.open('cache-name-v' + '"%SW_CACHE_VERSION%""')...
 * 
 *  - "%SW_ASSET_FILES%": The coma-separated list of assets generated by webpack for pre-cache purposes. Use "%SW_ASSET_FILES%" variable in your SW. Please note the double quotes around "%SW_ASSET_FILES%":
 * 
 *      cache.addAll(["%SW_ASSET_FILES%"]);
 * 
 * Notes:
 * 
 *  - When developing with webpack dev server, the file will be watched for changes.
 *  - When building assets, the file will be interpolated and copied to the destination folder configured in your webpack config.
 * 
 * Usage:
 * 
 *  const path = require('path');
 *  const InterpolateSWPlugin = require('./webpack.interpolate.sw.plugin');
 *
 *  var webpackConfig = {
 *    ...
 *    plugins: [
 *      new InterpolateSWPlugin({
 *        // Your source sw template full path. File having variables to be replaced.
 *        from: path.resolve(__dirname, './public/sw.js'),
 *        // Destination file inside your build directory. This file will have variables replaced already.
 *        to: 'sw.js',
 *        // Activate or deactivate replacement of the version variable %SW_CACHE_VERSION%
 *        replaceCacheVersion: true | false,
 *        // Activate or deactivate replacement of the files variable %SW_ASSET_FILES%
 *        replaceAssetFiles: true | false,
 *      }),
 *    ]
 *  };
 */
class InterpolateSWPlugin {
  constructor(options) {

    let defaults = {
      from: '',
      to: '',
      replaceCacheVersion: false,
      replaceAssetFiles: false,
    };

    this.options = Object.assign(defaults, options);

  }

  /**
   * Verifies we have all necesary configuration
   */
  _validOptions() {

    if (!this.options || 
        !this.options.from || !this.options.from.length ||
        !this.options.to   || !this.options.to.length) {
          return false;
        }

    return true;
  }

  /**
   * Gets a comma-separated list of compiled assets by webpack.
   * 
   * @param {*} compilation: currentwebpack compilation object.
   */
  _getCommaSeparatedAssetList (compilation) {

    let assetList = '';
    
    if (compilation && compilation.assets) {

      assetList = Object
        .keys(compilation.assets)
        .map(asset => '"' + asset + '"')
        .join(',\n');

    }

    return assetList;
      
  }

  /**
   * Make interpolations to the service worker, and copy it from origin to destination.
   * 
   * @param {*} compilation: Webpack compilation object provided by webpack compiler.
   * @param {*} callback: Webpack callbat to be called once task is finished. Provided by webpack plugin event.
   */
  _interpolateSW (compilation, callback) {
    
    // If we do not have all necesary configuration we exit
    if (!this._validOptions()) {
      console.log('InterpolateSWPlugin error: invalid options in: ', options);
      callback();
      return;
    }
    
    fs.readFile(this.options.from, 'utf8', (error, fileContent) => {
      
      if (error) {
        console.log('InterpolateSWPlugin error: from file not found (' + this.options.from + '). Make sure it is a full path and not a relative path.');
        callbak();
        return;
      }

      if (this.options.replaceAssetFiles) {
        fileContent = fileContent.replace(/"%SW_ASSET_FILES%"/gi, this._getCommaSeparatedAssetList (compilation));
      }

      if (this.options.replaceCacheVersion) {
        fileContent = fileContent.replace(/"%SW_CACHE_VERSION%"/gi, new Date().getTime());
      }
      
      // Insert this destination file into the Webpack build as a new file asset
      compilation.assets[this.options.to] = {
        source: function() {
          return fileContent;
        },
        size: function() {
          return fileContent.length;
        }
      };
        
      callback();
    
    });
  }

  /**
   * Apply will be called by webpack, so we can gain access to the compiler and all the events
   * 
   * @param {*} compiler : Current webpack compiler. This will be passed by webpack
   * 
   */
  apply(compiler) {

    let options = this.options;
    let _interpolateSW = this._interpolateSW.bind(this);

    compiler.plugin("after-compile", (compilation, callback) => {

      // Add the service worker template to dependecies. Now this file is being watched.
      compilation.fileDependencies.push(options.from);

      _interpolateSW (compilation, callback);
    });

  }
}

module.exports = InterpolateSWPlugin;
